---
# Created via 
# flux create secret git my-secret-name \
# --private-key-file=/my/absolute/path/to/key/file.pem \
# --url=ssh://git@github.com/my-org-name/my-repo-name \
# --export > flux-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: gitops-auth
  namespace: flux-system
stringData:
  identity: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    ...
    -----END OPENSSH PRIVATE KEY-----
  identity.pub: |
    ssh-rsa ...
  known_hosts: ...

