---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-cli-test
  namespace: sfera
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-cli-test
  template:
    metadata:
      labels:
        app: aws-cli-test
    spec:
      containers:
        - name: awscli
          image: amazon/aws-cli:2.32.16
          volumeMounts:
            - name: sfera-data-db
              mountPath: /app/database
            - name: sfera-caddy
              mountPath: /app/caddy
      volumes:
        - name: sfera-caddy
          persistentVolumeClaim:
            claimName: sfera-caddy
        - name: sfera-data-db
          persistentVolumeClaim:
            claimName: sfera-data-db
