# wireguard-hub-deployment.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: wg-hub
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wg-hub-sa
  namespace: wg-hub
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireguard-hub
  namespace: wg-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wireguard-hub
  template:
    metadata:
      labels:
        app: wireguard-hub
    spec:
      serviceAccountName: wg-hub-sa
      hostNetwork: true                      # bind to host network so UDP 51820 is reachable
      hostPID: true
      containers:
      - name: wireguard
        image: ghcr.io/linuxserver/wireguard:1.0.20250521
        securityContext:
          privileged: true                   # needs CAP_NET_ADMIN, etc.
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Europe/Rome"
        volumeMounts:
        - name: wg-config
          mountPath: /config                  # linuxserver image stores conf in /config
      - name: wg-manager
        image: busybox:1.36
        command: ["/bin/sh","-c","sleep 3600"] # placeholder, you can add a small manager container later
        securityContext:
          privileged: true
        volumeMounts:
        - name: wg-config
          mountPath: /etc/wireguard-management
      volumes:
      - name: wg-config
        hostPath:
          path: /etc/wireguard            # persistent store for configs and peer files
          type: DirectoryOrCreate
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wg-easy
  namespace: wg-hub
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: wg-easy
  strategy:
    # Restrict to a Single wg-easy instance, on redeploys it will tear down the old one before bring a new one up.
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wg-easy
    spec:
      containers:
        - name: wg-easy
          # Specify external hostname and port as environment variables
          env:
            - name: WG_HOST
              value: wg.hostname.com
            - name: WG_PORT
              value: "30000"
          image: ghcr.io/wg-easy/wg-easy
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 51820
              name: wg
              protocol: UDP
            - containerPort: 51821
              name: http
              protocol: TCP
          # Use the http server for pod health checks
          livenessProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: http
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: http
            timeoutSeconds: 1
          startupProbe:
            failureThreshold: 30
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: http
            timeoutSeconds: 1
          # Give pod permissions to modify iptables and load the wireguard kernel module
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
          # Persistent storage location
          volumeMounts:
            - mountPath: /etc/wireguard
              name: config
      restartPolicy: Always
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: wg-easy-storage-claim
